---
name: Win32-API-Interface
version: 0.0001_02
author:
  - 'Sascha Kiefer, L<esskar@cpan.org>'
abstract: ~
license: perl
requires:
  Win32::API: 0.41
provides:
  Win32::API::Interface:
    file: lib/Win32/API/Interface.pm
    version: 0.0001_02
generated_by: Module::Build version 0.2611
